# Generated by Django 3.0.8 on 2020-07-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('upload', models.ImageField(blank=True, height_field='picture_height', null=True, upload_to='', width_field='picture_width')),
            ],
        ),
    ]
